import { useState } from "react";
import { ImagePlus, Trash2, Check } from "lucide-react";
const API = import.meta.env.VITE_API_URL || "";
async function request(path, options = {}) { const response = await fetch(`${API}${path}`, { headers: { ...(options.body && !(options.body instanceof FormData) ? { "Content-Type": "application/json" } : {}), "x-admin-token": localStorage.getItem("aviator_admin_token") || "" }, ...options }); if (!response.ok) throw new Error(`Erreur API ${response.status}`); return response.json(); }
export default function AdminMediaPanel({ data, refresh }) {
  const [file, setFile] = useState(null); const [uploading, setUploading] = useState(false); const [error, setError] = useState("");
  const [editingId, setEditingId] = useState(null); const [altText, setAltText] = useState("");
  const upload = async (event) => { event.preventDefault(); if (!file) return; setUploading(true); setError(""); try { const form = new FormData(); form.append("file", file); await request("/api/admin/media", { method: "POST", body: form }); setFile(null); event.target.reset(); refresh(); } catch (uploadError) { setError(uploadError.message); } finally { setUploading(false); } };
  const remove = async (asset) => { if (window.confirm(`Supprimer ${asset.originalName} ?`)) { await request(`/api/admin/media/${asset.id}`, { method: "DELETE" }); refresh(); } };
  const startEdit = (asset) => { setEditingId(asset.id); setAltText(asset.altText || ""); };
  const saveAlt = async () => { if (!editingId) return; await request(`/api/admin/media/${editingId}`, { method: "PATCH", body: JSON.stringify({ alt_text: altText }) }); setEditingId(null); refresh(); };
  return <section className="border border-border bg-background p-5 sm:p-7"><div className="flex items-start gap-3"><ImagePlus className="mt-1 h-5 w-5 text-navy" /><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">Contenu</p><h2 className="mt-1 font-heading text-2xl font-bold">Médiathèque</h2><p className="mt-2 text-sm text-muted-foreground">Images JPEG, PNG, WebP ou GIF, 5 Mo maximum.</p></div></div><form onSubmit={upload} className="mt-6 flex flex-wrap gap-3"><input required type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(event) => setFile(event.target.files?.[0] || null)} className="border border-border px-3 py-2 text-sm" /><button disabled={uploading} className="bg-navy px-4 py-2 text-xs font-bold uppercase text-white disabled:opacity-50">{uploading ? "Import..." : "Importer"}</button></form>{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.map((asset) => <div key={asset.id} className="border border-border p-3"><img src={`${API}${asset.url}`} alt={asset.altText || asset.originalName} className="aspect-video w-full object-cover" />{editingId === asset.id ? <div className="mt-2 flex items-center gap-2"><input value={altText} onChange={(event) => setAltText(event.target.value)} className="w-full border border-border bg-background px-2 py-1.5 text-xs focus:border-navy focus:outline-none" placeholder="Texte alternatif (SEO)" aria-label="Texte alternatif" /><button onClick={saveAlt} className="p-1.5 text-navy" aria-label="Enregistrer le texte alternatif"><Check className="h-4 w-4" /></button></div> : <div className="mt-2 flex items-center justify-between gap-2"><button onClick={() => startEdit(asset)} className="min-w-0 flex-1 truncate text-left text-xs hover:underline" title="Modifier le texte alternatif">{asset.altText || asset.originalName}</button><div className="flex shrink-0 items-center gap-1"><button onClick={() => startEdit(asset)} className="p-2 text-muted-foreground hover:text-navy" aria-label="Modifier le texte alternatif"><ImagePlus className="h-4 w-4" /></button><button onClick={() => remove(asset)} className="p-2 text-destructive" aria-label={`Supprimer ${asset.originalName}`}><Trash2 className="h-4 w-4" /></button></div></div>}</div>)}{!data.length && <p className="text-sm text-muted-foreground">Aucun média.</p>}</div></section>;
}