import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import AdminModal from "./AdminModal";
const API = import.meta.env.VITE_API_URL || "http://localhost:3001";
async function request(path, options = {}) { const response = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json", "x-admin-token": localStorage.getItem("aviator_admin_token") || "" }, ...options }); if (!response.ok) throw new Error(`Erreur API ${response.status}`); return response.json(); }
const empty = { name: "", slug: "", title_fr: "", title_darija: "", subtitle_fr: "", subtitle_darija: "", image_url: "", active: true };
export default function AdminPromotionsPanelComplete({ data, refresh }) {
  const [open, setOpen] = useState(false); const [media, setMedia] = useState([]); const [form, setForm] = useState(empty);
  const openCreate = async () => { const result = await request("/api/admin/media?page=1&limit=100"); setMedia(result.data || result); setForm(empty); setOpen(true); };
  const save = async (event) => { event.preventDefault(); await request("/api/admin/promotions", { method: "POST", body: JSON.stringify(form) }); setOpen(false); refresh(); };
  const toggle = async (promotion) => { await request(`/api/admin/promotions/${promotion.id}`, { method: "PATCH", body: JSON.stringify({ active: !promotion.active, title_fr: promotion.titleFr, title_darija: promotion.titleDarija, subtitle_fr: promotion.subtitleFr, subtitle_darija: promotion.subtitleDarija, background_color: promotion.backgroundColor, text_color: promotion.textColor, accent_color: promotion.accentColor, image_url: promotion.imageUrl, coupon_code: promotion.couponCode }) }); refresh(); };
  const remove = async (promotion) => { if (window.confirm(`Supprimer ${promotion.name} ?`)) { await request(`/api/admin/promotions/${promotion.id}`, { method: "DELETE" }); refresh(); } };
  return <section className="border border-border bg-background p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">Marketing</p><h2 className="mt-1 font-display text-2xl font-bold">Promotions</h2></div><button onClick={openCreate} className="flex items-center gap-2 bg-navy px-4 py-3 text-xs font-bold uppercase text-white"><Plus className="h-4 w-4" />Nouvelle campagne</button></div><div className="mt-6 divide-y divide-border border-y border-border">{data.map((promotion) => <div key={promotion.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><strong>{promotion.name}</strong><p className="text-xs text-muted-foreground">{promotion.titleFr} · {promotion.titleDarija || "Darija à compléter"}</p></div><div className="flex gap-2"><button onClick={() => toggle(promotion)} className={`px-3 py-2 text-xs font-bold ${promotion.active ? "bg-accent-lime text-navy" : "bg-muted text-muted-foreground"}`}>{promotion.active ? "Active" : "Inactive"}</button><button onClick={() => remove(promotion)} className="border border-border p-2 text-destructive" aria-label={`Supprimer ${promotion.name}`}><Trash2 className="h-4 w-4" /></button></div></div>)}</div><AdminModal open={open} title="Créer une promotion" onClose={() => setOpen(false)}><form onSubmit={save} className="space-y-3"><input required placeholder="Nom" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="w-full border border-border px-3 py-2 text-sm" /><input required placeholder="Slug" value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} className="w-full border border-border px-3 py-2 text-sm" /><input required placeholder="Titre français" value={form.title_fr} onChange={(e) => setForm({ ...form, title_fr: e.target.value })} className="w-full border border-border px-3 py-2 text-sm" /><input placeholder="Titre Darija" value={form.title_darija} onChange={(e) => setForm({ ...form, title_darija: e.target.value })} className="w-full border border-border px-3 py-2 text-sm" /><textarea placeholder="Sous-titre français" value={form.subtitle_fr} onChange={(e) => setForm({ ...form, subtitle_fr: e.target.value })} className="w-full border border-border px-3 py-2 text-sm" /><select value={form.image_url} onChange={(e) => setForm({ ...form, image_url: e.target.value })} className="w-full border border-border px-3 py-2 text-sm"><option value="">Aucune image</option>{media.map((asset) => <option key={asset.id} value={asset.url}>{asset.originalName}</option>)}</select><button className="w-full bg-navy py-3 text-xs font-bold uppercase text-white">Créer la promotion</button></form></AdminModal></section>;
}
