import { useState } from "react";
import { Trash2 } from "lucide-react";
const API = import.meta.env.VITE_API_URL || "";
async function request(path, options = {}) { const response = await fetch(`${API}${path}`, { headers: { ...(options.body && !(options.body instanceof FormData) ? { "Content-Type": "application/json" } : {}), "x-admin-token": localStorage.getItem("aviator_admin_token") || "" }, ...options }); if (!response.ok) throw new Error(`Erreur API ${response.status}`); return response.json(); }
export default function AdminReturnsPanel({ data, refresh }) {
  const items = Array.isArray(data) ? data : [];
  const [busy, setBusy] = useState("");
  const shortId = (id) => String(id || "").slice(0, 8);
  const update = async (id, status) => { setBusy(id); try { await request(`/api/admin/returns/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }); refresh(); } finally { setBusy(""); } };
  const remove = async (id) => { if (window.confirm("Supprimer définitivement cette demande de retour ?")) { await request(`/api/admin/returns/${id}`, { method: "DELETE" }); refresh(); } };
  return <section className="border border-border bg-background p-5 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">Opérations</p><h2 className="mt-1 font-display text-2xl font-bold">Retours & remboursements</h2><div className="admin-list-scroll mt-6 divide-y divide-border border-y border-border">{items.map((item) => { const id = item.id || item.orderId || item.returnId || shortId(item.createdAt) || "RT"; return <div key={id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><strong className="font-mono text-sm">{shortId(id)}</strong>{item.reason || item.reasonText ? <p className="mt-1 text-xs text-muted-foreground">{item.reason || item.reasonText}{item.phone ? ` · ${item.phone}` : ""}</p> : (item.phone ? <p className="mt-1 text-xs text-muted-foreground">{item.phone}</p> : null)}{item.orderNumber ? <p className="mt-1 text-xs text-muted-foreground">Commande {item.orderNumber}</p> : null}<p className="mt-1 text-xs text-muted-foreground">{item.stockRestored ? "Stock restauré" : "Stock non restauré"}</p></div><div className="flex items-center gap-2"><select disabled={busy === id} value={item.status || "requested"} onChange={(event) => update(id, event.target.value)} className="border border-border bg-background px-3 py-2 text-xs"><option value="requested">Demandé</option><option value="approved">Accepté</option><option value="rejected">Refusé</option><option value="completed">Terminé</option></select><button disabled={busy === id} onClick={() => remove(id)} className="p-2 text-destructive" aria-label="Supprimer la demande"><Trash2 className="h-4 w-4" /></button></div></div>; })}{!items.length && <p className="py-10 text-center text-sm text-muted-foreground">Aucune demande de retour.</p>}</div></section>;
}