import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import AdminModal from "./AdminModal";
const API = import.meta.env.VITE_API_URL || "http://localhost:3001";
async function request(path, options = {}) { const response = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json", "x-admin-token": localStorage.getItem("aviator_admin_token") || "" }, ...options }); if (!response.ok) throw new Error(`Erreur API ${response.status}`); return response.json(); }
export default function AdminUsersPanel({ data, refresh }) {
  const [open, setOpen] = useState(false); const [roles, setRoles] = useState([]); const [form, setForm] = useState({ email: "", name: "", password: "", role_id: "" });
  const create = async (event) => { event.preventDefault(); await request("/api/admin/users", { method: "POST", body: JSON.stringify(form) }); setOpen(false); setForm({ email: "", name: "", password: "", role_id: "" }); refresh(); };
  const openCreate = async () => { setRoles(await request("/api/admin/roles")); setOpen(true); };
  const toggle = async (user) => { await request(`/api/admin/users/${user.id}`, { method: "PATCH", body: JSON.stringify({ active: !user.active }) }); refresh(); };
  const remove = async (user) => { if (window.confirm(`Supprimer ${user.email} ?`)) { await request(`/api/admin/users/${user.id}`, { method: "DELETE" }); refresh(); } };
  return <section className="border border-border bg-background p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">Sécurité</p><h2 className="mt-1 font-display text-2xl font-bold">Utilisateurs admin</h2></div><button onClick={openCreate} className="flex items-center gap-2 bg-navy px-4 py-3 text-xs font-bold uppercase text-white"><Plus className="h-4 w-4" />Nouvel utilisateur</button></div><div className="mt-6 divide-y divide-border border-y border-border">{data.map((user) => <div key={user.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><strong>{user.name}</strong><p className="text-xs text-muted-foreground">{user.email} · {user.roles?.map((role) => role.name).join(", ") || "Aucun rôle"}</p></div><div className="flex gap-2"><button onClick={() => toggle(user)} className={`px-3 py-2 text-xs font-bold ${user.active ? "bg-accent-lime text-navy" : "bg-muted text-muted-foreground"}`}>{user.active ? "Actif" : "Inactif"}</button><button onClick={() => remove(user)} className="border border-border p-2 text-destructive" aria-label={`Supprimer ${user.email}`}><Trash2 className="h-4 w-4" /></button></div></div>)}{!data.length && <p className="py-10 text-center text-sm text-muted-foreground">Aucun utilisateur.</p>}</div><AdminModal open={open} title="Créer un utilisateur admin" onClose={() => setOpen(false)}><form onSubmit={create} className="space-y-4"><input required type="text" placeholder="Nom" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="w-full border border-border px-4 py-3 text-sm" /><input required type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="w-full border border-border px-4 py-3 text-sm" /><input required minLength={12} type="password" placeholder="Mot de passe (12 caractères minimum)" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="w-full border border-border px-4 py-3 text-sm" /><select value={form.role_id} onChange={(e) => setForm({ ...form, role_id: e.target.value })} className="w-full border border-border px-4 py-3 text-sm"><option value="">Sans rôle</option>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select><button className="w-full bg-navy py-3 text-xs font-bold uppercase text-white">Créer</button></form></AdminModal></section>;
}
