import { useState } from "react";
import { Eye, UserPlus } from "lucide-react";
import AdminModal from "./AdminModal";
const API = import.meta.env.VITE_API_URL || "http://localhost:3001";
async function request(path) { const response = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json", "x-admin-token": localStorage.getItem("aviator_admin_token") || "" } }); if (!response.ok) throw new Error(`Erreur API ${response.status}`); return response.json(); }
export default function AdminCustomersPanel({ data }) {
  const [selected, setSelected] = useState(null); const [orders, setOrders] = useState([]);
  const open = async (customer) => { const result = await request(`/api/admin/orders?search=${encodeURIComponent(customer.phone)}&limit=100`); setOrders(result.data || result); setSelected(customer); };
  return <section className="border border-border bg-background p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">CRM</p><h2 className="mt-1 font-display text-2xl font-bold">Clients</h2></div><button className="flex items-center gap-2 border border-border px-4 py-3 text-xs font-bold uppercase"><UserPlus className="h-4 w-4" />Créer une commande</button></div><div className="mt-6 overflow-x-auto border-y border-border"><div className="grid min-w-[720px] grid-cols-[1.5fr_1fr_0.8fr_0.8fr_0.5fr] gap-4 border-b border-border bg-secondary px-4 py-3 text-[10px] font-bold uppercase tracking-wider text-muted-foreground"><span>Client</span><span>Ville</span><span>Commandes</span><span>Dépensé</span><span /></div>{data.map((customer) => <div key={customer.phone} className="grid min-w-[720px] grid-cols-[1.5fr_1fr_0.8fr_0.8fr_0.5fr] items-center gap-4 border-b border-border px-4 py-4 last:border-0"><div><strong>{customer.name || "Client invité"}</strong><p className="mt-1 text-xs text-muted-foreground">{customer.phone}</p></div><span className="text-sm">{customer.city}</span><span className="text-sm">{customer.orders}</span><strong className="text-sm">{(customer.totalSpent || 0).toLocaleString("fr-FR")} DH</strong><button onClick={() => open(customer)} className="border border-border p-2" aria-label={`Voir ${customer.name || customer.phone}`}><Eye className="h-4 w-4" /></button></div>)}{!data.length && <p className="px-4 py-10 text-center text-sm text-muted-foreground">Aucun client enregistré.</p>}</div><AdminModal open={Boolean(selected)} title={selected?.name || "Client invité"} onClose={() => setSelected(null)}>{selected && <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><div className="border border-border p-4"><p className="text-xs text-muted-foreground">Téléphone</p><strong>{selected.phone}</strong></div><div className="border border-border p-4"><p className="text-xs text-muted-foreground">Commandes</p><strong>{selected.orders}</strong></div><div className="border border-border p-4"><p className="text-xs text-muted-foreground">Total dépensé</p><strong>{(selected.totalSpent || 0).toLocaleString("fr-FR")} DH</strong></div></div><div><h3 className="font-display text-lg font-bold">Historique</h3><div className="mt-3 divide-y divide-border border-y border-border">{orders.map((order) => <div key={order.id} className="flex justify-between py-3 text-sm"><span className="font-mono">{order.orderNumber}</span><span>{order.status} · {(order.total / 100).toLocaleString("fr-FR")} DH</span></div>)}{!orders.length && <p className="py-6 text-sm text-muted-foreground">Aucune commande trouvée.</p>}</div></div></div>}</AdminModal></section>;
}
