import { useState } from "react";
import { CheckSquare, ImagePlus, Square } from "lucide-react";
import { AdminProductsPanel } from "./AdminCatalogPanels";
import { adminRequest as request } from "@/lib/adminApi";
export default function AdminProductsBulkPanel({ data, refresh }) {
  const [selected, setSelected] = useState([]); const [error, setError] = useState("");
  const allSelected = data.length > 0 && selected.length === data.length;
  const toggleAll = () => setSelected(allSelected ? [] : data.map((item) => item.id));
  const toggle = (id) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const removeSelected = async () => { if (!selected.length || !window.confirm(`Supprimer ${selected.length} produit(s) ?`)) return; try { await Promise.all(selected.map((id) => request(`/api/admin/products/${id}`, { method: "DELETE" }))); setSelected([]); refresh(); } catch (requestError) { setError(requestError.message); } };
  return <section className="border border-border bg-background p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">Catalogue</p><h2 className="mt-1 font-heading text-2xl font-bold">Produits & stock</h2></div><div className="flex gap-2">{selected.length > 0 && <button onClick={removeSelected} className="border border-destructive px-3 py-2 text-xs font-bold text-destructive">Supprimer {selected.length}</button>}<button onClick={() => document.getElementById("new-product-trigger")?.click()} className="bg-navy px-4 py-3 text-xs font-bold uppercase text-white">Nouveau produit</button></div></div><div className="mt-6 flex items-center gap-3 border-y border-border bg-secondary px-3 py-3 text-xs text-muted-foreground"><button onClick={toggleAll} aria-label="Tout sélectionner" className="p-1">{allSelected ? <CheckSquare className="h-4 w-4 text-navy" /> : <Square className="h-4 w-4" />}</button>{selected.length ? `${selected.length} sélectionné(s)` : "Sélectionner des produits pour les actions groupées"}</div><div className="divide-y divide-border border-b border-border">{data.map((product) => <div key={product.id} className="flex flex-wrap items-center gap-4 py-4"><button onClick={() => toggle(product.id)} aria-label={`Sélectionner ${product.name}`} className="p-1">{selected.includes(product.id) ? <CheckSquare className="h-4 w-4 text-navy" /> : <Square className="h-4 w-4" />}</button>{product.images?.[0] ? <img src={product.images[0]} alt="" className="h-12 w-12 object-cover" /> : <span className="flex h-12 w-12 items-center justify-center bg-muted"><ImagePlus className="h-4 w-4 text-muted-foreground" /></span>}<div className="min-w-[180px] flex-1"><strong>{product.name}</strong><p className="text-xs text-muted-foreground">{product.slug} · {product.color_name || "Couleur non définie"}</p></div><span className="text-sm font-semibold">{Number(product.price || 0).toLocaleString("fr-FR")} DH</span><span className={`text-sm font-bold ${product.stock < 5 ? "text-destructive" : "text-navy"}`}>{product.stock} stock</span></div>)}{!data.length && <p className="py-10 text-center text-sm text-muted-foreground">Aucun produit.</p>}</div>{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}<div className="hidden"><AdminProductsPanel data={data} refresh={refresh} /></div></section>;
}
