import { useState } from "react";
import { ImagePlus, Trash2 } from "lucide-react";
const API = import.meta.env.VITE_API_URL || "http://localhost:3001";
async function request(path, options = {}) { const response = await fetch(`${API}${path}`, { headers: { "x-admin-token": localStorage.getItem("aviator_admin_token") || "" }, ...options }); if (!response.ok) throw new Error(`Erreur API ${response.status}`); return response.json(); }
export default function AdminMediaPanel({ data, refresh }) {
  const [file, setFile] = useState(null); const [uploading, setUploading] = useState(false); const [error, setError] = useState("");
  const upload = async (event) => { event.preventDefault(); if (!file) return; setUploading(true); setError(""); try { const form = new FormData(); form.append("file", file); await request("/api/admin/media", { method: "POST", body: form }); setFile(null); event.target.reset(); refresh(); } catch (uploadError) { setError(uploadError.message); } finally { setUploading(false); } };
  const remove = async (asset) => { if (window.confirm(`Supprimer ${asset.originalName} ?`)) { await request(`/api/admin/media/${asset.id}`, { method: "DELETE" }); refresh(); } };
  return <section className="border border-border bg-background p-5 sm:p-7"><div className="flex items-start gap-3"><ImagePlus className="mt-1 h-5 w-5 text-navy" /><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">Contenu</p><h2 className="mt-1 font-display text-2xl font-bold">Media library</h2><p className="mt-2 text-sm text-muted-foreground">Images JPEG, PNG, WebP ou GIF, 5 Mo maximum.</p></div></div><form onSubmit={upload} className="mt-6 flex flex-wrap gap-3"><input required type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(event) => setFile(event.target.files?.[0] || null)} className="border border-border px-3 py-2 text-sm" /><button disabled={uploading} className="bg-navy px-4 py-2 text-xs font-bold uppercase text-white disabled:opacity-50">{uploading ? "Import..." : "Importer"}</button></form>{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.map((asset) => <div key={asset.id} className="border border-border p-3"><img src={`${API}${asset.url}`} alt={asset.altText || asset.originalName} className="aspect-video w-full object-cover" /><div className="mt-2 flex items-center justify-between gap-2"><p className="truncate text-xs">{asset.originalName}</p><button onClick={() => remove(asset)} className="p-2 text-destructive" aria-label={`Supprimer ${asset.originalName}`}><Trash2 className="h-4 w-4" /></button></div></div>)}{!data.length && <p className="text-sm text-muted-foreground">Aucun média.</p>}</div></section>;
}
