import { useEffect, useState } from "react";
import { Bell, Check, ChevronLeft, CreditCard, Globe2, Menu, Package, Plus, ShieldCheck, Tag } from "lucide-react";
import { AdminCategoriesPanel } from "@/components/admin/AdminCatalogPanels";
import AdminProductsPanel from "@/components/admin/AdminProductsBulkPanel";
import { AdminCouponsPanel } from "@/components/admin/AdminOperationsPanels";
import AdminOrdersPanel from "@/components/admin/AdminOrdersBulkPanel";
import AdminReturnsPanel from "@/components/admin/AdminReturnsPanel";
import AdminCustomersPanel from "@/components/admin/AdminCustomersPanel";
import AdminPromotionsPanel from "@/components/admin/AdminPromotionsPanelComplete";
import AdminRolesPanel from "@/components/admin/AdminRolesPanel";
import AdminUsersPanel from "@/components/admin/AdminUsersPanelComplete";
import AdminCmsPanel from "@/components/admin/AdminCmsPanel";
import AdminMediaPanel from "@/components/admin/AdminMediaPanel";
import AdminDashboardPanel from "@/components/admin/AdminDashboardPanel";
import AdminInventoryPanel from "@/components/admin/AdminInventoryPanel";
import AdminPaymentMethodsPanel from "@/components/admin/AdminPaymentMethodsPanel";
import AdminSettingsPanel from "@/components/admin/AdminSettingsPanel";
import AdminExportsPanel from "@/components/admin/AdminExportsPanel";

const API = import.meta.env.VITE_API_URL || "http://localhost:3001";
const request = async (path, options) => {
  const response = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json", "x-admin-token": localStorage.getItem("aviator_admin_token") || "" }, ...options });
  if (response.status === 401) {
    localStorage.removeItem("aviator_admin_token");
    window.dispatchEvent(new CustomEvent("aviator-admin-expired"));
  }
  if (!response.ok) throw new Error(`Erreur API ${response.status}`);
  return response.json();
};

const navGroups = [
  { title: "Pilotage", items: [["dashboard", "Vue d'ensemble", Package], ["commandes", "Commandes", Package], ["customers", "Clients", Package], ["returns", "Retours", Package], ["exports", "Exports & rapports", Package], ["audit-logs", "Journal d'activité", Package], ["notifications", "Notifications", Package], ["roles", "Rôles & permissions", ShieldCheck], ["users", "Utilisateurs admin", ShieldCheck]] },
  { title: "Catalogue", items: [["produits", "Produits", Package], ["categories", "Catégories", Package], ["variants", "Variantes & stock", Package], ["inventory", "Inventory", Package]] },
  { title: "Vente", items: [["shipping-zones", "Livraison", Package], ["coupons", "Coupons", Tag], ["promotions", "Promotions", ShieldCheck], ["payment-methods", "Moyens de paiement", CreditCard]] },
  { title: "Contenu", items: [["avis", "Avis à modérer", Check], ["cms", "Pages CMS", Package], ["media", "Media library", Package]] },
  { title: "Réglages", items: [["settings", "SEO & tracking", Globe2]] },
];
const tabs = navGroups.flatMap((group) => group.items);
const apiTabs = { commandes: "orders", produits: "products", "shipping-zones": "shipping-zones", coupons: "coupons", promotions: "promotions", avis: "reviews", cms: "cms/pages", media: "media", inventory: "inventory" };
const navPermission = { dashboard: "dashboard.view", commandes: "orders.view", customers: "customers.view", returns: "returns.view", exports: "reports.export", "audit-logs": "audit_logs.view", notifications: "notifications.view", roles: "roles.view", users: "users.view", produits: "products.view", categories: "categories.view", variants: "variants.view", inventory: "inventory.view", "shipping-zones": "shipping.view", coupons: "discounts.view", promotions: "promotions.view", "payment-methods": "payments.view", avis: "reviews.view", cms: "cms.view", media: "media.view", settings: "settings.view" };

export default function Admin() {
  const [authenticated, setAuthenticated] = useState(() => Boolean(localStorage.getItem("aviator_admin_token")));
  const [permissions, setPermissions] = useState(() => { try { return JSON.parse(localStorage.getItem("aviator_admin_permissions") || "[]"); } catch { return []; } });
  const [tab, setTab] = useState(() => { try { const stored = JSON.parse(localStorage.getItem("aviator_admin_permissions") || "[]"); return stored.includes("orders.view") ? "commandes" : "dashboard"; } catch { return "dashboard"; } });
  const [data, setData] = useState([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [page, setPage] = useState(1);
  const [meta, setMeta] = useState(null);
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [sidebarCollapsed, setSidebarCollapsed] = useState(() => localStorage.getItem("aviator_admin_sidebar") === "collapsed");
  const load = async () => {
    try {
      setError("");
      setLoading(true);
      if (tab === "dashboard") setData(await request("/api/admin/dashboard"));
      else if (tab === "variants") setData(await request("/api/admin/variants"));
      else if (tab === "settings") setData(await request("/api/admin/settings"));
      else if (tab === "exports") setData([]);
      else {
        const params = new URLSearchParams({ page: String(page), limit: "20" });
        if (search) params.set("search", search);
        if (statusFilter) params.set("status", statusFilter);
        const result = await request(`/api/admin/${apiTabs[tab] || tab}?${params}`);
        setData(result?.data || result);
        setMeta(result?.pages ? result : null);
      }
    } catch (err) { setError(err.message); }
    finally { setLoading(false); }
  };
  useEffect(() => {
    if (authenticated) load();
  }, [authenticated, tab, page, search, statusFilter]);
  useEffect(() => {
    const expire = () => setAuthenticated(false);
    window.addEventListener("aviator-admin-expired", expire);
    return () => window.removeEventListener("aviator-admin-expired", expire);
  }, []);

  if (!authenticated) return <AdminLogin onSuccess={(result) => { setPermissions(result.permissions || []); setAuthenticated(true); setTab(result.permissions?.includes("orders.view") ? "commandes" : "dashboard"); }} />;

  return (
    <div className="min-h-screen bg-secondary text-navy">
      <header className="border-b border-border bg-navy text-white">
        <div className="container-edge flex items-center justify-between gap-4 py-4"><div className="flex items-center gap-4"><button onClick={() => setSidebarCollapsed((value) => { const next = !value; localStorage.setItem("aviator_admin_sidebar", next ? "collapsed" : "expanded"); return next; })} className="border border-white/15 p-2 hover:bg-white/10" aria-label={sidebarCollapsed ? "Développer la navigation" : "Réduire la navigation"}>{sidebarCollapsed ? <Menu className="h-4 w-4" /> : <ChevronLeft className="h-4 w-4" />}</button><div><p className="text-[10px] uppercase tracking-[0.22em] text-accent-lime">The Aviator · Administration</p><h1 className="mt-1 font-display text-2xl font-bold">{tab === "dashboard" ? "Vue d'ensemble" : navGroups.flatMap((group) => group.items).find(([key]) => key === tab)?.[1] || "Back-office"}</h1></div></div><div className="flex items-center gap-3"><button className="border border-white/15 p-2 text-white/80 hover:bg-white/10" aria-label="Notifications"><Bell className="h-4 w-4" /></button><button onClick={async () => { const token = localStorage.getItem("aviator_admin_token"); await fetch(`${API}/api/admin/logout`, { method: "POST", headers: { "Content-Type": "application/json", "x-admin-token": token || "" }, body: JSON.stringify({ token }) }); localStorage.removeItem("aviator_admin_token"); localStorage.removeItem("aviator_admin_permissions"); setAuthenticated(false); }} className="border border-white/20 px-3 py-2 text-xs font-bold uppercase tracking-wider text-white hover:bg-white/10">Déconnexion</button></div></div>
      </header>
      {tab !== "dashboard" && tab !== "exports" && <div className="container-edge flex flex-wrap gap-3 pt-6"><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Rechercher dans la liste..." className="border border-border bg-background px-3 py-2 text-sm" /><select value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value); setPage(1); }} className="border border-border bg-background px-3 py-2 text-sm"><option value="">Tous les statuts</option><option value="draft">Brouillon</option><option value="published">Publié</option><option value="pending">En attente</option><option value="approved">Approuvé</option><option value="requested">Demandé</option></select></div>}
      <div className={`container-edge grid gap-8 py-8 ${sidebarCollapsed ? "lg:grid-cols-[72px_1fr]" : "lg:grid-cols-[220px_1fr]"}`}>
        <nav className="space-y-6">{navGroups.map((group) => { const visibleItems = group.items.filter(([key]) => permissions.includes(navPermission[key])); return visibleItems.length ? <div key={group.title}><p className={`mb-2 px-3 text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground ${sidebarCollapsed ? "sr-only" : ""}`}>{group.title}</p><div className="space-y-1">{visibleItems.map(([key, label, Icon]) => <button key={key} onClick={() => setTab(key)} title={sidebarCollapsed ? label : undefined} className={`flex w-full items-center gap-3 border-l-2 px-4 py-3 text-left text-sm font-semibold transition-colors ${tab === key ? "border-accent-lime bg-navy text-white" : "border-transparent bg-background hover:border-border hover:bg-muted"}`}><Icon className="h-4 w-4 shrink-0" />{!sidebarCollapsed && label}</button>)}</div></div> : null; })}</nav>
        <main>{error && <div className="mb-5 border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{error}</div>}{loading ? <section className="border border-border bg-background p-10 text-center text-sm text-muted-foreground">Chargement sécurisé...</section> : <>{tab === "dashboard" && <Dashboard data={data} />}{tab === "roles" && <AdminRolesPanel data={data} refresh={load} />}{tab === "users" && <AdminUsersPanel data={data} refresh={load} />}{tab === "cms" && <AdminCmsPanel data={data} refresh={load} />}{tab === "media" && <AdminMediaPanel data={data} refresh={load} />}{tab === "commandes" && <AdminOrdersPanel data={data} refresh={load} />}{tab === "customers" && <AdminCustomersPanel data={data} />}{tab === "returns" && <AdminReturnsPanel data={data} refresh={load} />}{tab === "audit-logs" && <SimpleList title="Journal d'activité" data={data} fields={["actor", "action", "entity"]} />}{tab === "notifications" && <SimpleList title="Notifications" data={data} fields={["type", "title", "message"]} />}{tab === "produits" && <AdminProductsPanel data={data} refresh={load} />}{tab === "categories" && <AdminCategoriesPanel data={data} refresh={load} />}{tab === "variants" && <Variants data={data} refresh={load} />}{tab === "inventory" && <AdminInventoryPanel data={data} refresh={load} />}{tab === "shipping-zones" && <ShippingZones data={data} refresh={load} />}{tab === "coupons" && <AdminCouponsPanel data={data} refresh={load} />}{tab === "promotions" && <AdminPromotionsPanel data={data} refresh={load} />}{tab === "avis" && <Reviews data={data} refresh={load} />}{tab === "payment-methods" && <AdminPaymentMethodsPanel data={data} refresh={load} />}{tab === "settings" && <AdminSettingsPanel data={data} refresh={load} />}{tab === "exports" && <AdminExportsPanel />}{meta && <Pagination meta={meta} page={page} onPageChange={setPage} />}</>}</main>
      </div>
    </div>
  );
}

function AdminLogin({ onSuccess }) {
  const [form, setForm] = useState({ email: "", password: "" });
  const [error, setError] = useState("");
  const submit = async (event) => {
    event.preventDefault();
    setError("");
    try {
      const result = await request("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) });
      if (!result.authenticated) throw new Error("Email ou mot de passe incorrect.");
      localStorage.setItem("aviator_admin_token", result.token);
      localStorage.setItem("aviator_admin_permissions", JSON.stringify(result.permissions || []));
      onSuccess(result);
    } catch (err) { setError(err.message); }
  };
  return <div className="flex min-h-screen items-center justify-center bg-[radial-gradient(circle_at_top_right,#d5e50022,transparent_35%),#f5f6f8] px-5"><form onSubmit={submit} className="w-full max-w-md border border-border bg-background p-8 shadow-xl sm:p-10"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center bg-navy font-display text-lg font-bold text-accent-lime">A</span><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-navy">The Aviator</p><p className="text-xs text-muted-foreground">Espace administrateur</p></div></div><h1 className="mt-8 font-display text-3xl font-bold">Connexion sécurisée</h1><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Accédez aux commandes, produits, promotions et avis.</p><label className="mt-6 block text-xs font-semibold uppercase tracking-wider text-muted-foreground">Email<input required type="email" autoComplete="username" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="mt-2 w-full border border-border px-4 py-3 text-sm focus:border-navy focus:outline-none" placeholder="admin@..." /></label><label className="mt-4 block text-xs font-semibold uppercase tracking-wider text-muted-foreground">Mot de passe<input required type="password" autoComplete="current-password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="mt-2 w-full border border-border px-4 py-3 text-sm focus:border-navy focus:outline-none" placeholder="Votre mot de passe" /></label>{error && <p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}<button className="mt-6 w-full bg-navy py-3.5 text-xs font-bold uppercase tracking-wider text-white transition-colors hover:bg-primary">Ouvrir le back-office</button><p className="mt-5 text-center text-[11px] text-muted-foreground">Session persistante révocable côté serveur.</p></form></div>;
}

function Panel({ title, children }) { return <section className="border border-border bg-background p-5 sm:p-7"><h2 className="font-display text-2xl font-bold">{title}</h2>{children}</section>; }
function Pagination({ meta, page, onPageChange }) { return <div className="mt-5 flex items-center justify-between border-t border-border pt-4 text-xs text-muted-foreground"><span>{meta.total} éléments · page {page} / {meta.pages}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => onPageChange(page - 1)} className="border border-border px-3 py-2 disabled:opacity-40">Précédent</button><button disabled={page >= meta.pages} onClick={() => onPageChange(page + 1)} className="border border-border px-3 py-2 disabled:opacity-40">Suivant</button></div></div>; }
function Dashboard({ data }) { return <AdminDashboardPanel data={data} onNavigate={() => undefined} />; }
function SimpleList({ title, data, fields }) { return <Panel title={title}><div className="mt-5 divide-y divide-border border-y border-border">{data.map((item) => <div key={item.id} className="py-4"><strong>{fields.map((field) => item[field]).filter(Boolean).join(" · ")}</strong><p className="mt-1 text-xs text-muted-foreground">{item.createdAt ? new Date(item.createdAt).toLocaleString("fr-FR") : ""}</p></div>)}{!data.length && <p className="py-10 text-center text-sm text-muted-foreground">Aucun élément.</p>}</div></Panel>; }
function Customers({ data }) { return <Panel title="Clients"><div className="mt-5 divide-y divide-border border-y border-border">{data.map((customer) => <div key={customer.phone} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><strong>{customer.name || "Client invité"}</strong><p className="mt-1 text-xs text-muted-foreground">{customer.phone} · {customer.city}</p></div><div className="text-right"><strong className="block">{customer.totalSpent.toLocaleString("fr-FR")} DH</strong><span className="text-xs text-muted-foreground">{customer.orders} commande{customer.orders > 1 ? "s" : ""}</span></div></div>)}</div>{!data.length && <p className="py-10 text-center text-sm text-muted-foreground">Aucun client enregistré.</p>}</Panel>; }
function Categories({ data, refresh }) { const [form, setForm] = useState({ name: "", slug: "", description: "" }); const save = async (event) => { event.preventDefault(); await request("/api/admin/categories", { method: "POST", body: JSON.stringify(form) }); setForm({ name: "", slug: "", description: "" }); refresh(); }; return <Panel title="Catégories"><form onSubmit={save} className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_2fr_auto]"><input required placeholder="Nom" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="border border-border px-3 py-2 text-sm" /><input required placeholder="Slug" value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} className="border border-border px-3 py-2 text-sm" /><input placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="border border-border px-3 py-2 text-sm" /><button className="bg-navy px-4 py-2 text-xs font-bold uppercase text-white">Ajouter</button></form><div className="mt-6 divide-y divide-border border-y border-border">{data.map((category) => <div key={category.id} className="flex items-center justify-between py-4"><div><strong>{category.name}</strong><p className="text-xs text-muted-foreground">/{category.slug} · {category.description}</p></div><span className={`px-2 py-1 text-xs font-bold ${category.active ? "bg-accent-lime" : "bg-muted"}`}>{category.active ? "Active" : "Inactive"}</span></div>)}</div></Panel>; }
function Orders({ data, refresh }) { return <Panel title="Commandes"><div className="mt-5 divide-y divide-border border-y border-border">{data.map((order) => <div key={order.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><strong className="font-mono text-sm">{order.orderNumber}</strong><p className="mt-1 text-xs text-muted-foreground">{order.firstName} {order.lastName} · {order.phone} · {order.city}</p></div><div className="flex items-center gap-3"><strong>{(order.total / 100).toLocaleString("fr-FR")} DH</strong><select value={order.status} onChange={async (event) => { await request(`/api/admin/orders/${order.id}`, { method: "PATCH", body: JSON.stringify({ status: event.target.value }) }); refresh(); }} className="border border-border bg-background px-3 py-2 text-xs"><option value="nouvelle">Nouvelle</option><option value="confirmee">Confirmée</option><option value="preparation">Préparation</option><option value="expediee">Expédiée</option><option value="livree">Livrée</option><option value="annulee">Annulée</option><option value="retour">Retour</option></select></div></div>)}{!data.length && <p className="py-10 text-center text-sm text-muted-foreground">Aucune commande.</p>}</div></Panel>; }
function Products({ data, refresh }) { const [form, setForm] = useState({ name: "", slug: "", price: "", stock: "", color_name: "Navy" }); const save = async (event) => { event.preventDefault(); await request("/api/admin/products", { method: "POST", body: JSON.stringify({ ...form, sizes: ["S", "M", "L", "XL", "XXL"], images: [] }) }); setForm({ name: "", slug: "", price: "", stock: "", color_name: "Navy" }); refresh(); }; return <Panel title="Produits & stock"><form onSubmit={save} className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><input required placeholder="Nom" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="border border-border px-3 py-2 text-sm" /><input required placeholder="Slug" value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} className="border border-border px-3 py-2 text-sm" /><input required type="number" placeholder="Prix DH" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} className="border border-border px-3 py-2 text-sm" /><input required type="number" placeholder="Stock" value={form.stock} onChange={(e) => setForm({ ...form, stock: e.target.value })} className="border border-border px-3 py-2 text-sm" /><button className="flex items-center justify-center gap-2 bg-navy px-4 py-2 text-xs font-bold uppercase text-white"><Plus className="h-4 w-4" />Ajouter</button></form><div className="mt-6 divide-y divide-border border-y border-border">{data.map((p) => <div key={p.id} className="flex items-center justify-between py-4"><div><strong>{p.name}</strong><p className="text-xs text-muted-foreground">{p.slug} · {p.colorName || p.color_name || "-"}</p></div><span className={`text-sm font-bold ${p.stock < 5 ? "text-destructive" : "text-navy"}`}>{p.stock} en stock</span></div>)}</div></Panel>; }
function Variants({ data, refresh }) { return <Panel title="Variantes & inventaire"><p className="mt-2 text-sm text-muted-foreground">Stock réel par SKU, taille et couleur.</p><div className="mt-5 divide-y divide-border border-y border-border">{data.map((variant) => <div key={variant.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><strong className="font-mono text-sm">{variant.sku}</strong><p className="mt-1 text-xs text-muted-foreground">{variant.color} · Taille {variant.size}</p></div><div className="flex items-center gap-2"><input defaultValue={variant.stock} type="number" min="0" className="w-20 border border-border px-2 py-2 text-sm" onBlur={async (event) => { await request(`/api/admin/variants/${variant.id}`, { method: "PATCH", body: JSON.stringify({ stock: event.target.value, price: variant.price / 100, low_stock_threshold: variant.lowStockThreshold }) }); refresh(); }} /><span className={`text-xs font-bold ${variant.stock <= variant.lowStockThreshold ? "text-destructive" : "text-muted-foreground"}`}>{variant.stock <= variant.lowStockThreshold ? "Stock faible" : "Disponible"}</span></div></div>)}{!data.length && <p className="py-10 text-center text-sm text-muted-foreground">Aucune variante.</p>}</div></Panel>; }
function ShippingZones({ data, refresh }) { return <Panel title="Zones de livraison"><div className="mt-5 divide-y divide-border border-y border-border">{data.map((zone) => <div key={zone.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><strong>{zone.city}</strong><p className="text-xs text-muted-foreground">{zone.region || "Maroc"} · {zone.deliveryTime}</p></div><div className="flex items-center gap-2"><input defaultValue={zone.fee / 100} type="number" className="w-24 border border-border px-2 py-2 text-sm" onBlur={async (event) => { await request(`/api/admin/shipping-zones/${zone.id}`, { method: "PATCH", body: JSON.stringify({ fee: event.target.value, free_threshold: zone.freeThreshold ? zone.freeThreshold / 100 : 0, delivery_time: zone.deliveryTime, active: zone.active }) }); refresh(); }} /><span className="text-xs">DH</span><span className={`px-2 py-1 text-xs font-bold ${zone.active ? "bg-accent-lime" : "bg-muted"}`}>{zone.active ? "Active" : "Inactive"}</span></div></div>)}</div></Panel>; }
function Coupons({ data, refresh }) { return <Panel title="Coupons"><div className="mt-5 divide-y divide-border border-y border-border">{data.map((coupon) => <div key={coupon.id} className="flex items-center justify-between py-4"><div><strong className="font-mono">{coupon.code}</strong><p className="text-xs text-muted-foreground">{coupon.discountType} · utilisé {coupon.usedCount} fois</p></div><button onClick={async () => { await request(`/api/admin/coupons/${coupon.id}`, { method: "PATCH", body: JSON.stringify({ active: !coupon.active }) }); refresh(); }} className={`px-3 py-1 text-xs font-bold ${coupon.active ? "bg-accent-lime text-navy" : "bg-muted text-muted-foreground"}`}>{coupon.active ? "Actif" : "Inactif"}</button></div>)}</div></Panel>; }
function Promotions({ data, refresh }) { return <Panel title="Promotions"><div className="mt-5 divide-y divide-border border-y border-border">{data.map((promotion) => <div key={promotion.id} className="flex items-center justify-between py-4"><div><strong>{promotion.name}</strong><p className="text-xs text-muted-foreground">{promotion.titleFr} · {promotion.titleDarija || "Darija à compléter"}</p></div><button onClick={async () => { await request(`/api/admin/promotions/${promotion.id}`, { method: "PATCH", body: JSON.stringify({ active: !promotion.active, title_fr: promotion.titleFr, title_darija: promotion.titleDarija, subtitle_fr: promotion.subtitleFr, subtitle_darija: promotion.subtitleDarija, background_color: promotion.backgroundColor, text_color: promotion.textColor, accent_color: promotion.accentColor, image_url: promotion.imageUrl, coupon_code: promotion.couponCode }) }); refresh(); }} className={`px-3 py-1 text-xs font-bold ${promotion.active ? "bg-accent-lime text-navy" : "bg-muted text-muted-foreground"}`}>{promotion.active ? "Active" : "Inactive"}</button></div>)}</div></Panel>; }
function Reviews({ data, refresh }) { return <Panel title="Avis à modérer"><div className="mt-5 divide-y divide-border border-y border-border">{data.map((review) => <div key={review.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><strong>{review.name} · {review.rating}/5</strong><p className="mt-1 text-sm text-muted-foreground">{review.comment}</p></div><div className="flex gap-2"><button onClick={async () => { await request(`/api/admin/reviews/${review.id}`, { method: "PATCH", body: JSON.stringify({ status: "approved" }) }); refresh(); }} className="bg-accent-lime px-3 py-2 text-xs font-bold">Approuver</button><button onClick={async () => { await request(`/api/admin/reviews/${review.id}`, { method: "PATCH", body: JSON.stringify({ status: "rejected" }) }); refresh(); }} className="border border-border px-3 py-2 text-xs font-bold">Rejeter</button></div></div>)}</div></Panel>; }
